// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xsvygheqrbnhmzlgnbyk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhzdnlnaGVxcmJuaG16bGduYnlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5ODg1NzgsImV4cCI6MjA1NzU2NDU3OH0.ZxmWvYbDcPbfAq-WT5G-vQRTIji0kincaEmh7knxx5s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);